<?php
return [
    "countries" => "countries",
    "cities" => "cities",
    "states" => "states",
    "land_create" => "land_create",
    "land_files" => "land_files",
    "land_create_id" => "land_create_id",
    'f_name' => 'f_name',
    'f_mimetype' => 'f_mimetype',
    'is_admin_approved' => 'is_admin_approved',
    'created_at' => 'created_at',
    'comment' => 'comment',
    'created_by' => 'created_by',
    'updated_at' => 'updated_at',
    'city' => 'city',
    'size' => 'size',
    'location' => 'location',
    'description' => 'description',
    'title' => 'title',
    'is_active' => 'is_active',
    'user' => 'user',
    'users' => 'users',
    'link' => 'link',
    "user_id" => "user_id",
    "is_super_admin" => "is_super_admin",
    "is_admin" => "is_admin",
    "primary_key" => "id",
    "lands" => "lands",
    "land_comments" => "land_comments",
];

?>