name: Harbourislandcommonage Deployment

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'resources/js/lib/tailwindcss.js'
jobs:
  setup-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]
        commit_msg: ["Fixes coding style"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with fail-fast
        uses: shivammathur/setup-php@21e092a3e0c2fabb77bf641337eced34a4bcd3cc
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, bz2, fileinfo, gd, gettext,mbstring,exif,mysqli,pdo_mysql
          tools: pint:1.16.1,phpdoc,composer:2.4.4
          coverage: none
      - name: check composer version
        run: composer --version
      - name: Run Pint
        run: pint --config configs/pint.json

      - name: Run PHPDoc
        run: phpdoc --config phpdoc.dist.xml

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@0b492c0d951b87f3cd12523a542dbd156c1dbc80
        with:
          commit_message: ${{ matrix.commit_msg }}
          branch: master
  nodejs-setup:
    runs-on: ubuntu-latest
    steps:

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.live', '.env');"

      - name: setup nodejs
        uses: actions/setup-node@48b90677b6048efbc723b11a94acb950d3f1ac36
        with:
          node-version: "18.18.0"
  project:
    needs: ['setup-php',"nodejs-setup"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        script_command:
          [
            "pwd && cd ~/public_html/website_7171ee6c && pwd && chmod u+x ./server_deploy.sh && ./server_deploy.sh",
          ]

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Install Node.js dependencies
        run: npm ci

      - name: setup 8GB memory heap for node JS
        run: |
          export NODE_OPTIONS="--max-old-space-size=8096"

      - name: Run npm
        run: |
          npm run prod

      # - name: Run linter prettier
      #   uses: wearerequired/lint-action@v2
      #   with:
      #     prettier: true
      #     prettier_auto_fix: true
      #     prettier_args: --config configs/.prettierrc.json
      #     prettier_extensions: "js,ts,html,css,tsx,json"

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASS}}
          server-dir: /

      - name: Running Scripts
        uses: appleboy/ssh-action@49751ff51697f88206b6c7a0f60f83d1a880b26d
        with:
          username: ${{secrets.SSH_USERNAME}}
          host: ${{secrets.IP_SERVER}}
          password: ${{ secrets.SSH_PASSWORD }}
          use_insecure_cipher: true
          script: ${{matrix.script_command}}
