name: Harbourislandcommonage Deployment

on:
  push:
    branches: ["master"]
jobs:
  setup-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]
        commit_msg: ["Fixes coding style"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with fail-fast
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, bz2, fileinfo, gd, gettext,mbstring,exif,mysqli,pdo_mysql
          tools: pint:1.16.1,phpdoc,composer:2.4.4
          coverage: none
      - name: check composer version
        run: composer --version
      - name: Run Pint
        run: pint --config configs/pint.json

      - name: Run PHPDoc
        run: phpdoc --config phpdoc.dist.xml

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ matrix.commit_msg }}
          branch: master

  laravel-deployment:
    needs: setup-php
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        script_command:
          [
            "pwd && cd ~/public_html/website_7171ee6c && pwd && chmod u+x ./server_deploy.sh && ./server_deploy.sh",
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.live', '.env');"

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          auto_fix: true

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASS}}
          server-dir: /

      - name: Running Scripts
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.SSH_USERNAME}}
          host: ${{secrets.IP_SERVER}}
          password: ${{ secrets.SSH_PASSWORD }}
          use_insecure_cipher: true
          script: ${{matrix.script_command}}
