name: Harbourislandcommonage Deployment

on:
  push:
    branches: [ "master" ]
jobs:
  laravel-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.live', '.env');"

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{secrets.FTP_SERVER}}
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASS}}
        server-dir: /

    - name: Running Scripts
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.SSH_USERNAME}}
        host: ${{secrets.IP_SERVER}}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd ~/public_html/website_7171ee6c && chmod u+x ./server_deploy.sh && ./server_deploy.sh'
