name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@21e092a3e0c2fabb77bf641337eced34a4bcd3cc
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: composer install

    # PHPStan Analysis
    # - name: PHPStan
    #   run: |
    #     composer require phpstan/phpstan
    #     vendor/bin/phpstan analyse --configuration=phpstan.neon

    # PHPCS Check
    # - name: PHPCS
    #   run: |
    #     composer require squizlabs/php_codesniffer
    #     vendor/bin/phpcs --standard=phpcs.xml

    # Security Checker
    - name: Security Check
      uses: symfonycorp/security-checker-action@e706dcce24c03714d146fcad711c3bfb4e9c08a9
      with:
        disable-exit-code: 1 # Prevent the action from failing on vulnerabilities

    # Upload results to GitHub Security
    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: ${{ github.workspace }}/results.sarif
